name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Yarn Dependencies
        run: yarn install --frozen-lockfile --silent

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier:check

      - name: Typecheck
        run: yarn typecheck
      
      - name: Double check
        run: npx playwright install && yarn test

      - name: Build
        env:
          COOKIE_SECRET: ${{ secrets.COOKIE_SECRET }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: yarn build